apiVersion: apps/v1
kind: Deployment
metadata:
  name: conference-demo
  namespace: test
  labels:
    app: conference-demo
    domain: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conference-demo
  template:
    metadata:
      labels:
        app: conference-demo
        domain: demo
    spec:
      containers:
        - name: conference-demo
          image: quay.io/nginx/nginx-unprivileged:1.28.0-alpine-perl
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          securityContext:
            runAsNonRoot: true
            privileged: false