apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    app: demo
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  serviceAccount: demo-service-account